version: "2.4"

services:
  app:
    image: app:${SERVICE}
    container_name: app_${SERVICE}
    build:
      dockerfile: services/app/Dockerfile
      context: .
    runtime: $DOCKER_RUNTIME
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace
      - GIT_PYTHON_REFRESH=quiet
      - MLFLOW_TRACKING_URI
      - MLFLOW_ARTIFACT_ROOT
    volumes:
      - .:/workspace
      - ./mlruns:/mlruns
    ports:
      - "8080:8080"
